mutation saveSubscription($subscription: SaveSubscriptionV2Input!) {
  saveSubscriptionV2(input: $subscription) {
    success
  }
}

# V2 of UpdateMonthlyBudgetConfig, updates the postgres DB
mutation UpdateSettings($inputs: UpdateMonthSettingsInput!) {
  updateMonthSettingsV2(inputs: $inputs) {
    success
  }
}

# Delete a transaction from PostgresDB
mutation DeleteTransactionByID($inputs: DeleteTransactionByIdV2Input!) {
  deleteTransactionByIdV2(inputs: $inputs) {
    success
  }
}

# Add a transaction to the Postgres DB
mutation AddTransactionV2($inputs: AddTransactionV2Input!) {
  addTransactionV2(inputs: $inputs) {
    success
  }
}

# update a transaction by ID
mutation UpdateTransactionByID($inputs: UpdateTransactionByIdV2Input!) {
  updateTransactionByIdV2(inputs: $inputs) {
    success
  }
}
