mutation saveSubscription($subscription: SubscriptionInput!) {
  saveSubscription(subscription: $subscription) {
    username
    notificationSubscription {
      endpoint
      expirationTime
      keys {
        p256Dh
        auth
      }
    }
  }
}

mutation UpdateMonthlyBudgetConfig($inputs: UpdateBudgetConfigInput!) {
  updateMonthlyBudgetConfig(inputs: $inputs) {
    ... on UpdateBudgetResponse {
      success
    }
    ... on GraphQLErrorObject {
      __typename
      code
      message
    }
  }
}

mutation UpdateMonthlyBudget($inputs: UpdateMonthlyBudgetInput!) {
  updateMonthlyBudget(inputs: $inputs) {
    ... on MonthlyBudget {
      __typename
      month
      totalSpending
      overBudgetAmount
      spending {
        id
        amount
        date
        description
        notes
      }
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
    }

    ... on GraphQLErrorObject {
      __typename
      code
      message
    }
  }
}

mutation AddSpendingItemByMonth($inputs: AddSpendingItemByMonthInput!) {
  addSpendingItemByMonth(inputs: $inputs) {
    ... on SuccessResponse {
      success
    }
    ...GraphQLErrorFields
  }
}
