fragment GraphQLErrorFields on GraphQLErrorObject {
  __typename
  code
  message
}

fragment GraphQLErrorFieldsV2 on GraphQLErrorObject {
  __typename
  code
  message
}

# Get monthly budget configuration
query SettingsPageData($year: Int!, $month: Month!) {
  monthlyBudgetConfig(year: $year, month: $month) {
    ... on BudgetConfig {
      __typename
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
    }
    ...GraphQLErrorFields
  }

  me {
    username
    firefly {
      enabled
      apiKey
      sourceAccount
    }
  }

  firefly {
    ... on FireflySuccessResponse {
      __typename
      accounts
    }
    ... on FireflyErrorObject {
      code
      message
    }
  }
}

# Get the budget for a specific month
query GetMonthBudget($year: Int!, $month: Month!) {
  monthlyBudget(year: $year, month: $month) {
    __typename
    ... on MonthlyBudget {
      __typename
      month
      totalSpending
      overBudgetAmount
      spending {
        id
        amount
        date
        description
        notes
      }
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
    }
    ...GraphQLErrorFields
  }
}

# Get frontend config
query getConfig {
  config {
    encryptionPublicKey
    vapidPublicKey
  }
}

# Get information about the currently authenticated user
query Me {
  me {
    username
  }
}

# Data required in the spending form
query SpendingItemForm($year: Int!, $month: Month!) {
  monthlyBudgetConfig(year: $year, month: $month) {
    ... on BudgetConfig {
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
    }
    ...GraphQLErrorFields
  }
}
