fragment GraphQLErrorFields on GraphQLErrorObject {
  __typename
  code
  message
}

fragment GraphQLErrorFieldsV2 on GraphQLErrorObject {
  __typename
  code
  message
}

# Get settings page data from the PostgresDB
query SettingsPageDataV2($year: Int!, $month: Month!) {
  monthSettingsV2(year: $year, month: $month) {
    settings {
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
      firefly {
        enabled
        apiKey
        sourceAccount
      }
    }
  }
  firefly {
    accounts
  }
}

# Query data for the home page, from the Postgres DB
query GetHomePageDataV2($inputs: HomePageV2Input!) {
  homePageV2(inputs: $inputs) {
    totalSpending
    totalBudget
    overSpending
    transactions {
      id
      amount
      date
      description
      notes
    }
    settings {
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
    }
  }
}

# Data for the SplitBudget component
query SplitBudgetData($year: Int!, $month: Month!) {
  monthSettingsV2(year: $year, month: $month) {
    settings {
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
    }
  }
}

# Get frontend config
query getConfig {
  config {
    encryptionPublicKey
    vapidPublicKey
  }
}

# Get information about the currently authenticated user
query Me {
  meV2 {
    username
  }
}

# Search for a transaction by ID from the PostgresDB
query SearchTransactionByID($inputs: SearchTransactionV2Inputs!) {
  searchTransactionV2(inputs: $inputs) {
    transaction {
      id
      amount
      date
      description
      notes
    }
  }
}

# # Data for the transaction form
# query TransactionFOrm($year: Int!, $month: Month!) {
#   monthSettingsV2(year: $year, month: $month) {
#     settings {
#       shawnPercentageAllocation
#       maggiePercentageAllocation
#     }
#   }
# }
