# Get monthly budget configuration
query GetMonthlyBudgetConfig($year: Int!, $month: Month!) {
  monthlyBudget(year: $year, month: $month) {
    ... on MonthlyBudget {
      budget {
        totalAllocation
        shawnPercentageAllocation
        shawnContributionAmount
        maggiePercentageAllocation
        maggieContributionAmount
      }
    }
    ... on GraphQLErrorObject {
      code
      message
    }
  }
}

# Get the budget for a specific month
query GetMonthBudget($year: Int!, $month: Month!) {
  monthlyBudget(year: $year, month: $month) {
    __typename
    ... on MonthlyBudget {
      __typename
      month
      totalSpending
      overBudgetAmount
      spending {
        id
        amount
        date
        description
        notes
      }
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
    }
    ... on GraphQLErrorObject {
      __typename
      code
      message
    }
  }
}

# Get frontend config
query getConfig {
  config {
    encryptionPublicKey
    vapidPublicKey
  }
}
