services:
  budget_tool_backend:
    container_name: budget_tool_backend
    build: ./backend
    image: ghcr.io/shawnyu5/budget_tool_backend:develop
    ports:
      - "3000:80"
    env_file:
      - ./backend/.env

  postgres:
    container_name: postgres
    image: docker.io/library/postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

