[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
axum = { version = "0.7.9", features = ["macros"] }
schemars = "0.8.21"
serde = { version = "1.0.215", features = ["derive"] }
simd-json = "0.14.3"
tokio = { version = "1.42.0", features = ["full"] }
toml = "0.8.19"
tower = "0.5.1"
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
   "env-filter",
   "std",
   "fmt",
] }
utoipa = "5.2.0"
common-axum = { path = "../../common-axum/" }
# common-axum = { git = "https://github.com/shawnyu5/common-axum", rev = "v1.1.0" }
mongodb = "3.1.0"
dotenvy = "0.15.7"
chrono = { version = "0.4.38", features = ["serde"] }
thiserror = "2.0.6"
rayon = "1.10.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
base64 = "0.22.1"
