[package]
name = "backend"
version = "1.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
schemars = "1.0.4"
simd-json = "0.17.0"
toml = "0.9.8"
tower = "0.5.1"
tracing = "0.1.41"
mongodb = "3.1.0"
dotenvy = "0.15.7"
thiserror = "2.0.12"
rayon = "1.10.0"
sha2 = "0.10.8"
base64 = "0.22.1"
utoipa = "5.2.0"
utoipa-axum = "0.2.0"
csv = "1.3.1"
web-push = "0.11.0"
async-graphql-axum = "7.0.17"
async-graphql = "7.0.17"
openssl = { version = "0.10.73", features = ["vendored"] }
jsonwebtoken = "9.3.1"
tokio-cron-scheduler = { version = "0.15.0", features = ["signal"] }
futures = "0.3.31"
chrono-tz = "0.10.3"
headers = "0.4.1"
axum-extra = { version = "0.12.5", features = ["cookie", "typed-header"] }


[dev-dependencies]
axum-test = "18.0.2"


[dependencies.axum]
version = "0.8.4"
features = ["macros"]

[dependencies.serde]
version = "1.0.215"
features = ["derive"]

[dependencies.tokio]
version = "1.42.0"
features = ["full"]

[dependencies.tower-http]
version = "0.6.2"
features = ["cors", "trace"]

[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter", "std", "fmt"]

[dependencies.common-axum]
git = "https://github.com/shawnyu5/common-axum"
rev = "v1.4.0"

[dependencies.chrono]
version = "0.4.38"
features = ["serde"]
