[package]
name = "backend"
version = "1.2.1"
edition = "2024"

[dependencies]
firefly_client = { path = "./firefly_client/" }

anyhow = "1.0.94"
schemars = "1.0.4"
simd-json = "0.17.0"
toml = "0.9.8"
tower = "0.5.1"
tracing = "0.1.41"
dotenvy = "0.15.7"
thiserror = "2.0.12"
rayon = "1.10.0"
sha2 = "0.10.8"
base64 = "0.22.1"
utoipa = "5.2.0"
utoipa-axum = "0.2.0"
csv = "1.3.1"
web-push = "0.11.0"
openssl = { version = "0.10.73", features = ["vendored"] } # Dependency of web-push...
async-graphql-axum = "7.0.17"
async-graphql = { version = "7.0.17", features = ["uuid", "chrono", "decimal"] }
jsonwebtoken = { version = "10.2.0", features = ["aws_lc_rs"] }
tokio-cron-scheduler = { version = "0.15.0", features = ["signal"] }
futures = "0.3.31"
chrono-tz = "0.10.3"
headers = "0.4.1"
axum-extra = { version = "0.12.5", features = ["cookie", "typed-header"] }
chacha20poly1305 = "0.10.1"
reqwest = { version = "^0.12" }
sqlx = { version = "0.8.6", features = [
   "chrono",
   "derive",
   "macros",
   "postgres",
   "runtime-tokio",
   "rust_decimal",
   "tls-rustls",
   "uuid",
   "migrate",
] }
uuid = { version = "1.21.0", features = ["v4"] }
rust_decimal = { version = "1.40.0", features = ["macros"] }
validator = { version = "0.20.0", features = ["derive"] }


[dev-dependencies]
axum-test = "18.0.2"
tracing-test = "0.2.6"


[dependencies.axum]
version = "0.8.4"
features = ["macros"]

[dependencies.serde]
version = "1.0.215"
features = ["derive"]

[dependencies.tokio]
version = "1.42.0"
features = ["full"]

[dependencies.tower-http]
version = "0.6.2"
features = ["cors", "trace"]

[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter", "std", "fmt"]

[dependencies.common-axum]
git = "https://github.com/shawnyu5/common-axum"
rev = "v1.4.0"

[dependencies.chrono]
version = "0.4.38"
features = ["serde"]
