# fly.toml app configuration file generated for budget-tool on 2024-12-18T22:05:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'budget-tool'
primary_region = 'yyz'

[build]

[env]
PORT = '8080'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
