"""
Errors that could happen during adding an item by month
"""
enum AddSpendingItemByMonthError {
	"""
	Failed to create / update transactions in firefly
	"""
	FIREFLY_UPDATE_FAILED
}

type AddSpendingItemByMonthErrorObject {
	code: AddSpendingItemByMonthError!
	message: String!
}

input AddSpendingItemByMonthInput {
	year: String!
	month: Month!
	spendingItem: SpendingItemInput!
}

union AddSpendingItemByMonthResponse = SuccessResponse | AddSpendingItemByMonthErrorObject

type AddTransactionResponseV2 {
	success: Boolean!
}

input AddTransactionV2Input {
	year: Int!
	month: Month!
	transaction: TransactionInput!
}

type BudgetConfig {
	"""
	Total allocated budget
	"""
	totalAllocation: Float!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Float!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Float!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Float!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Float!
}

input BudgetConfigInput {
	"""
	Total allocated budget
	"""
	totalAllocation: Float!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Float!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Float!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Float!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Float!
}

"""
Implement the DateTime<FixedOffset> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

scalar Decimal

input DeleteSpendingItemByIdInput {
	year: Int!
	month: Month!
	"""
	The ID of the spending item to delete
	"""
	id: String!
}

input DeleteTransactionByIdV2Input {
	transactionId: UUID!
}

type DeleteTransactionByIdV2Response {
	success: Boolean!
}

"""
Firefly related settings
"""
type FireflySettings {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	Must call `User.decrypt_firefly_api_key()` to get the decrypted version
	"""
	apiKey: String
	"""
	Base64 encoded nounce used to encrypt / decrypt the API key
	"""
	encryptionNounce: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

"""
Firefly related settings
"""
input FireflySettingsInput {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	Must call `User.decrypt_firefly_api_key()` to get the decrypted version
	"""
	apiKey: String
	"""
	Base64 encoded nounce used to encrypt / decrypt the API key
	"""
	encryptionNounce: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

"""
Firefly related settings
"""
type FireflySettingsV2 {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	Must call `User.decrypt_firefly_api_key()` to get the decrypted version
	"""
	apiKey: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

"""
Firefly related settings
"""
input FireflySettingsV2Input {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	Must call `User.decrypt_firefly_api_key()` to get the decrypted version
	"""
	apiKey: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

type FireflySuccessResponse {
	"""
	List of accounts this user has
	"""
	accounts: [String!]
}

"""
Frontend configuration
"""
type FrontendConfig {
	"""
	Base 64 encoded public key used for encryption
	"""
	encryptionPublicKey: String!
	"""
	Non base 64 encoded VAPID public key used for sending notifications
	"""
	vapidPublicKey: String!
}

"""
GraphQL error codes
"""
enum GraphQLErrorCode {
	"""
	Something went wrong on the server side. Typically response 500
	"""
	SERVER_ERROR
	"""
	Failed to fetch budget for some reason. Typically response 404
	"""
	FAILED_TO_FETCH_BUDGET
	INVALID_FIREFLY_API_KEY
	"""
	Failed to create / update transactions in firefly
	"""
	FIREFLY_UPDATE_FAILED
}

type GraphQLErrorObject {
	code: GraphQLErrorCode!
	message: String!
}

"""
Data on the home screen
"""
type HomePage {
	"""
	Total $ spend in this month
	"""
	totalSpending: Decimal!
	"""
	Total allocated budget
	"""
	totalBudget: Decimal!
	"""
	Amount that was over spent
	"""
	overSpending: Decimal!
	"""
	All transactions for this month
	"""
	transactions: [Transaction!]!
	"""
	Settings for the particular month
	"""
	settings: Settings!
}

input HomePageV2Input {
	year: Int!
	month: Month!
}

enum Month {
	January
	February
	March
	April
	May
	June
	July
	August
	September
	October
	November
	December
}

"""
Budget details for single month
"""
type MonthlyBudget {
	"""
	The month
	"""
	month: Month!
	"""
	Budget details
	"""
	budget: BudgetConfig!
	"""
	Total spending for the month. Including any over budget amount
	"""
	totalSpending: Float!
	"""
	Amount over budget for the month. 0 means not over budget.
	"""
	overBudgetAmount: Float!
	"""
	List of spent items
	"""
	spending: [SpendingItem!]!
	"""
	The month it was carried over from
	If the setting are not carried over from a previous month, this value will be empty
	"""
	carriedOverFrom: Month
}

union MonthlyBudgetConfigResponse = BudgetConfig | GraphQLErrorObject

"""
Budget details for single month
"""
input MonthlyBudgetInput {
	"""
	The month
	"""
	month: Month!
	"""
	Budget details
	"""
	budget: BudgetConfigInput!
	"""
	Total spending for the month. Including any over budget amount
	"""
	totalSpending: Float!
	"""
	Amount over budget for the month. 0 means not over budget.
	"""
	overBudgetAmount: Float!
	"""
	List of spent items
	"""
	spending: [SpendingItemInput!]!
	"""
	The month it was carried over from
	If the setting are not carried over from a previous month, this value will be empty
	"""
	carriedOverFrom: Month
}

union MonthlyBudgetResponse = MonthlyBudget | GraphQLErrorObject

type MonthlySettingsResponse {
	settings: Settings!
}

type MutationRoot {
	"""
	Save a notification subscription for a user
	The user is extracted from the JWT
	"""
	saveSubscription(subscription: SubscriptionInput!): User! @deprecated(reason: "Save to the PostgresDB instead")
	"""
	Update the budget configuration for a specific month
	"""
	updateMonthlyBudgetConfig(inputs: UpdateBudgetConfigInput!): UpdateBudgetConfigResponse! @deprecated(reason: "use `update_month_settings_v2` to save to the PostgresDB")
	"""
	Update the settings for a specific month, in the Postgres DB
	"""
	updateMonthSettingsV2(inputs: UpdateMonthSettingsInput!): UpdateMonthSettingsResponse!
	"""
	Add a spending item to a month
	"""
	addSpendingItemByMonth(inputs: AddSpendingItemByMonthInput!): AddSpendingItemByMonthResponse! @deprecated(reason: "use `add_transaction_v2` to save to the PostgresDB")
	"""
	Delete a spending item by ID. If the item doesnt exist, this handler will not do anything
	"""
	deleteSpendingItemById(inputs: DeleteSpendingItemByIdInput!): MonthlyBudgetResponse! @deprecated(reason: "use `delete_transaction_by_id_v2` to delete from the PostgresDB")
	"""
	Delete a transaction by ID from the PostgresDB
	"""
	deleteTransactionByIdV2(inputs: DeleteTransactionByIdV2Input!): DeleteTransactionByIdV2Response!
	"""
	Update a spending item by ID
	"""
	updateSpendingItemById(inputs: UpdateSpendingItemByIdInput!): UpdateSpendingItemByIdResponse!
	"""
	Add a transaction
	"""
	addTransactionV2(inputs: AddTransactionV2Input!): AddTransactionResponseV2!
	"""
	Update a transaction by ID
	"""
	updateTransactionByIdV2(inputs: UpdateTransactionByIdV2Input!): UpdateTransactionByIdV2Response!
	"""
	Update the budget for a specific month
	"""
	updateMonthlyBudget(inputs: UpdateMonthlyBudgetInput!): MonthlyBudgetResponse! @deprecated(reason: "Do not use this handler anymore. Prefer the more finegrained updates instead")
	me(inputs: UpdateMe!): UpdateMeResponse!
}

type NotificationKeys {
	p256Dh: String!
	auth: String!
}

input NotificationKeysInput {
	p256Dh: String!
	auth: String!
}

"""
Stuff the browser sends to do the notification handshake
"""
type NotificationSubscription {
	endpoint: String!
	expirationTime: Int
	keys: NotificationKeys!
}

"""
Stuff the browser sends to do the notification handshake
"""
input NotificationSubscriptionInput {
	endpoint: String!
	expirationTime: Int
	keys: NotificationKeysInput!
}

"""
Root of the query
"""
type QueryRoot {
	"""
	Configuration for the frontend to consume
	"""
	config: FrontendConfig!
	"""
	Get the budget for a specific month in a year
	
	* `year`: the year
	* `month`: the month
	"""
	monthlyBudget(year: Int!, month: Month!): MonthlyBudgetResponse!
	monthlyBudgetConfig(year: Int!, month: Month!): MonthlyBudgetConfigResponse!
	"""
	Get the settings for a particular month. Retrieves the data from PostgresDB
	"""
	monthSettingsV2(year: Int!, month: Month!): MonthlySettingsResponse!
	me: User!
	"""
	Retrieve information from Firefly it self
	"""
	firefly: FireflySuccessResponse!
	"""
	Search for a spending item by time and ID
	"""
	searchSpendingItem(inputs: SearchSpendingItemInput!): SpendingItem
	"""
	Get data to display on the home page
	"""
	homePageV2(inputs: HomePageV2Input!): HomePage!
	"""
	Search for a transaction from the PostgresDB
	"""
	searchTransactionV2(inputs: SearchTransactionV2Inputs!): SearchTransactionV2Response!
}

input SearchSpendingItemInput {
	year: Int!
	month: Month!
	id: String!
}

input SearchTransactionV2Inputs {
	"""
	ID of the transaction to search for
	"""
	transactionId: UUID!
}

type SearchTransactionV2Response {
	transaction: Transaction
}

"""
Data on the settings page
"""
input SettingInput {
	"""
	Total allocated budget
	"""
	totalAllocation: Decimal!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Decimal!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Decimal!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Decimal!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Decimal!
	"""
	Firefly related settings
	"""
	firefly: FireflySettingsV2Input!
}

"""
Data on the settings page
"""
type Settings {
	"""
	Total allocated budget
	"""
	totalAllocation: Decimal!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Decimal!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Decimal!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Decimal!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Decimal!
	"""
	Firefly related settings
	"""
	firefly: FireflySettingsV2!
}

"""
A single transaction
"""
type SpendingItem {
	"""
	A unique identifier
	"""
	id: String!
	"""
	The dollar amount
	"""
	amount: Float!
	"""
	The date
	"""
	date: String!
	"""
	Date in RFC3339 format, in Eastern timezone
	"""
	dateRfc3339: String
	"""
	Description of the purchase
	"""
	description: String!
	"""
	Additional notes
	"""
	notes: String
}

"""
A single transaction
"""
input SpendingItemInput {
	"""
	A unique identifier
	"""
	id: String!
	"""
	The dollar amount
	"""
	amount: Float!
	"""
	The date
	"""
	date: String!
	"""
	Date in RFC3339 format, in Eastern timezone
	"""
	dateRfc3339: String
	"""
	Description of the purchase
	"""
	description: String!
	"""
	Additional notes
	"""
	notes: String
}

input SubscriptionInput {
	endpoint: String!
	p256Dh: String!
	auth: String!
	expirationTime: Int
}

type SuccessResponse {
	success: Boolean!
}

"""
Represent a single transaction
"""
type Transaction {
	id: UUID!
	amount: Decimal!
	date: DateTime!
	description: String!
	notes: String!
}

"""
Represent a single transaction
"""
input TransactionInput {
	id: UUID!
	amount: Decimal!
	date: DateTime!
	description: String!
	notes: String!
}

"""
A UUID is a unique 128-bit number, stored as 16 octets. UUIDs are parsed as
Strings within GraphQL. UUIDs are used to assign unique identifiers to
entities without requiring a central allocating authority.

# References

* [Wikipedia: Universally Unique Identifier](http://en.wikipedia.org/wiki/Universally_unique_identifier)
* [RFC4122: A Universally Unique Identifier (UUID) URN Namespace](http://tools.ietf.org/html/rfc4122)
"""
scalar UUID

input UpdateBudgetConfigInput {
	"""
	The year of the budget to update
	"""
	year: Int!
	"""
	The month of the budget to update
	"""
	month: Month!
	"""
	The new budget config
	"""
	budgetConfig: BudgetConfigInput!
	"""
	Firefly related settings for the current user
	"""
	firefly: FireflySettingsInput!
}

union UpdateBudgetConfigResponse = UpdateBudgetResponse | GraphQLErrorObject

type UpdateBudgetResponse {
	success: Boolean!
}

input UpdateMe {
	user: UserInput!
}

type UpdateMeResponse {
	success: Boolean!
}

input UpdateMonthSettingsInput {
	"""
	The year of the budget to update
	"""
	year: Int!
	"""
	The month of the budget to update
	"""
	month: Month!
	"""
	Updated settings
	"""
	settings: SettingInput!
}

type UpdateMonthSettingsResponse {
	success: Boolean!
}

input UpdateMonthlyBudgetInput {
	year: Int!
	month: Month!
	budget: MonthlyBudgetInput!
}

input UpdateSpendingItemByIdInput {
	year: Int!
	month: Month!
	"""
	The new spending item to update
	"""
	spendingItem: SpendingItemInput!
}

type UpdateSpendingItemByIdResponse {
	success: Boolean!
}

input UpdateTransactionByIdV2Input {
	transactionId: UUID!
	amount: Decimal!
	date: DateTime!
	description: String
	notes: String
}

type UpdateTransactionByIdV2Response {
	success: Boolean!
}

"""
Represents a user
"""
type User {
	"""
	Username of the user
	"""
	username: String!
	"""
	Notification subscription
	"""
	notificationSubscription: NotificationSubscription!
	lastUpdated: String
	firefly: FireflySettings
}

"""
Represents a user
"""
input UserInput {
	"""
	Username of the user
	"""
	username: String!
	"""
	Notification subscription
	"""
	notificationSubscription: NotificationSubscriptionInput!
	lastUpdated: String
	firefly: FireflySettingsInput
}

"""
Marks an element of a GraphQL schema as no longer supported.
"""
directive @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | ENUM_VALUE
"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
schema {
	query: QueryRoot
	mutation: MutationRoot
}
