type AddTransactionResponseV2 {
	success: Boolean!
}

input AddTransactionV2Input {
	year: Int!
	month: Month!
	transaction: TransactionInput!
}

"""
Implement the DateTime<FixedOffset> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

scalar Decimal

input DeleteTransactionByIdV2Input {
	transactionId: UUID!
}

type DeleteTransactionByIdV2Response {
	success: Boolean!
}

"""
Firefly related settings
"""
type FireflySettingsV2 {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	"""
	apiKey: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

"""
Firefly related settings
"""
input FireflySettingsV2Input {
	"""
	If the user has enabled Firefly integration
	"""
	enabled: Boolean!
	"""
	Encrypted firefly API key, required if `enabled` = true
	"""
	apiKey: String
	"""
	The source account to create the transaction in
	"""
	sourceAccount: String
}

type FireflyV2SuccessResponse {
	"""
	List of accounts this user has
	"""
	accounts: [String!]!
}

"""
Frontend configuration
"""
type FrontendConfig {
	"""
	Base 64 encoded public key used for encryption
	"""
	encryptionPublicKey: String!
	"""
	Non base 64 encoded VAPID public key used for sending notifications
	"""
	vapidPublicKey: String!
}

input GetTransactionsInput {
	"""
	The number of results to return
	"""
	limit: Int!
}

type GetTransactionsResponse {
	transactions: [Transaction!]!
}

"""
Data on the home screen
"""
type HomePage {
	"""
	Total $ spend in this month
	"""
	totalSpending: Decimal!
	"""
	Total allocated budget
	"""
	totalBudget: Decimal!
	"""
	Amount that was over spent
	"""
	overSpending: Decimal!
	"""
	All transactions for this month
	"""
	transactions: [Transaction!]!
	"""
	Settings for the particular month
	"""
	settings: Settings!
}

input HomePageV2Input {
	year: Int!
	month: Month!
}

enum Month {
	January
	February
	March
	April
	May
	June
	July
	August
	September
	October
	November
	December
}

type MonthlySettingsResponse {
	settings: Settings!
}

type MutationRoot {
	"""
	Save the user subscription to Postgres DB
	"""
	saveSubscriptionV2(input: SaveSubscriptionV2Input!): SaveSubscriptionV2Response!
	"""
	Update the settings for a specific month, in the Postgres DB
	"""
	updateMonthSettingsV2(inputs: UpdateMonthSettingsInput!): UpdateMonthSettingsResponse!
	"""
	Delete a transaction by ID from the PostgresDB
	"""
	deleteTransactionByIdV2(inputs: DeleteTransactionByIdV2Input!): DeleteTransactionByIdV2Response!
	"""
	Add a transaction
	"""
	addTransactionV2(inputs: AddTransactionV2Input!): AddTransactionResponseV2!
	"""
	Update a transaction by ID
	"""
	updateTransactionByIdV2(inputs: UpdateTransactionByIdV2Input!): UpdateTransactionByIdV2Response!
}

"""
Root of the query
"""
type QueryRoot {
	"""
	Configuration for the frontend to consume
	"""
	config: FrontendConfig!
	"""
	Get the settings for a particular month. Retrieves the data from PostgresDB
	If there are no settings for the month, check the previous month. If it exists, insert the previous month settings into the month being queried
	"""
	monthSettingsV2(year: Int!, month: Month!): MonthlySettingsResponse!
	"""
	Returns the content of the JWT
	"""
	meV2: UserV2!
	"""
	Query information from the Firefly server
	"""
	fireflyV2: FireflyV2SuccessResponse
	"""
	Get data to display on the home page
	"""
	homePageV2(inputs: HomePageV2Input!): HomePage!
	"""
	Search for a transaction from the PostgresDB
	"""
	searchTransactionV2(inputs: SearchTransactionV2Inputs!): SearchTransactionV2Response!
	"""
	Get a list of most recent transactions
	"""
	getTransactions(inputs: GetTransactionsInput!): GetTransactionsResponse!
}

input SaveSubscriptionV2Input {
	endpoint: String!
	expirationTime: String
	p256Dh: String!
	auth: String!
}

type SaveSubscriptionV2Response {
	success: Boolean!
}

input SearchTransactionV2Inputs {
	"""
	ID of the transaction to search for
	"""
	transactionId: UUID!
}

type SearchTransactionV2Response {
	transaction: Transaction
}

"""
Data on the settings page
"""
input SettingInput {
	"""
	Total allocated budget
	"""
	totalAllocation: Decimal!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Decimal!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Decimal!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Decimal!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Decimal!
	"""
	Firefly related settings
	"""
	firefly: FireflySettingsV2Input!
}

"""
Data on the settings page
"""
type Settings {
	"""
	Total allocated budget
	"""
	totalAllocation: Decimal!
	"""
	Shawn percentage allocation
	"""
	shawnPercentageAllocation: Decimal!
	"""
	Shawn contribution amount. The frontend is responsible for computing this value
	"""
	shawnContributionAmount: Decimal!
	"""
	Maggie percentage allocation
	"""
	maggiePercentageAllocation: Decimal!
	"""
	Maggie contribution amount. The frontend is responsible for computing this value
	"""
	maggieContributionAmount: Decimal!
	"""
	Firefly related settings
	"""
	firefly: FireflySettingsV2!
}

"""
Represent a single transaction
"""
type Transaction {
	id: UUID!
	amount: Decimal!
	date: DateTime!
	description: String!
	notes: String!
}

"""
Represent a single transaction
"""
input TransactionInput {
	id: UUID!
	amount: Decimal!
	date: DateTime!
	description: String!
	notes: String!
}

"""
A UUID is a unique 128-bit number, stored as 16 octets. UUIDs are parsed as
Strings within GraphQL. UUIDs are used to assign unique identifiers to
entities without requiring a central allocating authority.

# References

* [Wikipedia: Universally Unique Identifier](http://en.wikipedia.org/wiki/Universally_unique_identifier)
* [RFC4122: A Universally Unique Identifier (UUID) URN Namespace](http://tools.ietf.org/html/rfc4122)
"""
scalar UUID

input UpdateMonthSettingsInput {
	"""
	The year of the budget to update
	"""
	year: Int!
	"""
	The month of the budget to update
	"""
	month: Month!
	"""
	Updated settings
	"""
	settings: SettingInput!
}

type UpdateMonthSettingsResponse {
	success: Boolean!
}

input UpdateTransactionByIdV2Input {
	transactionId: UUID!
	amount: Decimal!
	date: DateTime!
	description: String
	notes: String
}

type UpdateTransactionByIdV2Response {
	success: Boolean!
}

type UserV2 {
	username: String!
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
schema {
	query: QueryRoot
	mutation: MutationRoot
}
