// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type HomeResponse = {
    version: string;
};

export type Month = 'January' | 'February' | 'March' | 'April' | 'May' | 'June' | 'July' | 'August' | 'September' | 'October' | 'November' | 'December';

export type NotificationBody = {
    body: string;
    title: string;
};

export type NotificationKeys = {
    auth: string;
    p256dh: string;
};

export type NotificationSendBody = {
    /**
     * The body of the notification
     */
    body: NotificationBody;
    /**
     * Data sent by the browser to do the handshake for the notification
     */
    subscription: NotificationSubscription;
};

/**
 * Stuff the browser sends to do the notification handshake
 */
export type NotificationSubscription = {
    endpoint: string;
    expirationTime?: string | null;
    keys: NotificationKeys;
};

export type AppVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppVersionErrors = {
    /**
     * Failed to get the vesion of the server
     */
    500: string;
};

export type AppVersionError = AppVersionErrors[keyof AppVersionErrors];

export type AppVersionResponses = {
    /**
     * Version of the server
     */
    200: HomeResponse;
};

export type AppVersionResponse = AppVersionResponses[keyof AppVersionResponses];

export type ValidateTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/validate-token';
};

export type ValidateTokenErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get update spending item
     */
    500: string;
};

export type ValidateTokenError = ValidateTokenErrors[keyof ValidateTokenErrors];

export type ValidateTokenResponses = {
    /**
     * The JWT token is still valid
     */
    200: unknown;
};

export type ValidateTokenV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/validate-token/v2';
};

export type ValidateTokenV2Errors = {
    /**
     * JWT has expired
     */
    403: string;
};

export type ValidateTokenV2Error = ValidateTokenV2Errors[keyof ValidateTokenV2Errors];

export type ValidateTokenV2Responses = {
    /**
     * The JWT token is still valid
     */
    200: unknown;
};

export type ExportCsvHandlerData = {
    body?: never;
    path: {
        /**
         * The year the spending item is in
         */
        year: string;
        /**
         * The month the spending item is in
         */
        month: Month;
    };
    query?: never;
    url: '/export/{year}/{month}/csv';
};

export type ExportCsvHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get update spending item
     */
    500: string;
};

export type ExportCsvHandlerError = ExportCsvHandlerErrors[keyof ExportCsvHandlerErrors];

export type ExportCsvHandlerResponses = {
    /**
     * Spending items in CSV format
     */
    200: string;
};

export type ExportCsvHandlerResponse = ExportCsvHandlerResponses[keyof ExportCsvHandlerResponses];

export type GraphqlHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphqlHandlerResponses = {
    /**
     * GraphQL response
     */
    200: unknown;
};

export type BasicAuthHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/basic';
};

export type BasicAuthHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
};

export type BasicAuthHandlerError = BasicAuthHandlerErrors[keyof BasicAuthHandlerErrors];

export type BasicAuthHandlerResponses = {
    /**
     * Login successful. Returns a JWT token
     */
    200: string;
};

export type BasicAuthHandlerResponse = BasicAuthHandlerResponses[keyof BasicAuthHandlerResponses];

export type BasicAuthHandlerV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/basic/v2';
};

export type BasicAuthHandlerV2Errors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
};

export type BasicAuthHandlerV2Error = BasicAuthHandlerV2Errors[keyof BasicAuthHandlerV2Errors];

export type BasicAuthHandlerV2Responses = {
    /**
     * Login successful. Returns a JWT token
     */
    200: string;
};

export type BasicAuthHandlerV2Response = BasicAuthHandlerV2Responses[keyof BasicAuthHandlerV2Responses];

export type SendNotificationHandlerData = {
    body: NotificationSendBody;
    path?: never;
    query?: never;
    url: '/notification/send';
};

export type SendNotificationHandlerResponses = {
    /**
     * Notification sent successfully
     */
    200: unknown;
};
