// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type BudgetConfig = {
    /**
     * Maggie contribution amount. The frontend is responsible for computing this value
     */
    maggieContributionAmount: number;
    /**
     * Maggie percentage allocation
     */
    maggiePercentageAllocation: number;
    /**
     * Shawn contribution amount. The frontend is responsible for computing this value
     */
    shawnContributionAmount: number;
    /**
     * Shawn percentage allocation
     */
    shawnPercentageAllocation: number;
    /**
     * Total allocated budget
     */
    totalAllocation: number;
};

export type HomeResponse = {
    version: string;
};

export type Month = 'January' | 'February' | 'March' | 'April' | 'May' | 'June' | 'July' | 'August' | 'September' | 'October' | 'November' | 'December';

/**
 * Budget details for single month
 */
export type MonthlyBudget = {
    /**
     * Budget details
     */
    budget: BudgetConfig;
    carriedOverFrom?: null | Month;
    /**
     * The month
     */
    month: Month;
    /**
     * Amount over budget for the month. 0 means not over budget.
     */
    overBudgetAmount: number;
    /**
     * List of spent items
     */
    spending: Array<SpendingItem>;
    /**
     * Total spending for the month. Including any over budget amount
     */
    totalSpending: number;
};

export type NotificationBody = {
    body: string;
    title: string;
};

export type NotificationKeys = {
    auth: string;
    p256dh: string;
};

export type NotificationSendBody = {
    /**
     * The body of the notification
     */
    body: NotificationBody;
    /**
     * Data sent by the browser to do the handshake for the notification
     */
    subscription: NotificationSubscription;
};

/**
 * Stuff the browser sends to do the notification handshake
 */
export type NotificationSubscription = {
    endpoint: string;
    expirationTime?: number | null;
    keys: NotificationKeys;
};

/**
 * A single transaction
 */
export type SpendingItem = {
    /**
     * The dollar amount
     */
    amount: number;
    /**
     * The date
     */
    date: string;
    /**
     * Description of the purchase
     */
    description: string;
    /**
     * A unique identifier
     */
    id: string;
    /**
     * Additional notes
     */
    notes?: string | null;
};

export type AppVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppVersionErrors = {
    /**
     * Failed to get the vesion of the server
     */
    500: string;
};

export type AppVersionError = AppVersionErrors[keyof AppVersionErrors];

export type AppVersionResponses = {
    /**
     * Version of the server
     */
    200: HomeResponse;
};

export type AppVersionResponse = AppVersionResponses[keyof AppVersionResponses];

export type ValidateTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/validate-token';
};

export type ValidateTokenErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get update spending item
     */
    500: string;
};

export type ValidateTokenError = ValidateTokenErrors[keyof ValidateTokenErrors];

export type ValidateTokenResponses = {
    /**
     * The JWT token is still valid
     */
    200: unknown;
};

export type ValidateTokenV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/validate-token/v2';
};

export type ValidateTokenV2Errors = {
    /**
     * JWT has expired
     */
    403: string;
};

export type ValidateTokenV2Error = ValidateTokenV2Errors[keyof ValidateTokenV2Errors];

export type ValidateTokenV2Responses = {
    /**
     * The JWT token is still valid
     */
    200: unknown;
};

export type GetMonthBudgetHandlerData = {
    body?: never;
    path: {
        /**
         * The year which to get the budget of
         */
        year: string;
        /**
         * The month's budget to get. The first letter of the month's name is expected to the captalized. ie `January`
         */
        month: Month;
    };
    query?: never;
    url: '/budget/{year}/{month}';
};

export type GetMonthBudgetHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * All months, the requested month and before does not contain any monthly budget
     */
    404: string;
    /**
     * Failed to get the requested month's budget
     */
    500: string;
};

export type GetMonthBudgetHandlerError = GetMonthBudgetHandlerErrors[keyof GetMonthBudgetHandlerErrors];

export type GetMonthBudgetHandlerResponses = {
    /**
     * The requested month's budget. If the request month does not have any budget records, this route will iterate back till either no more months to check, a budget is encountered. The returned budget will have no spending, all the fields are correct, and matches the request
     */
    200: MonthlyBudget;
};

export type GetMonthBudgetHandlerResponse = GetMonthBudgetHandlerResponses[keyof GetMonthBudgetHandlerResponses];

export type UpdateBudgetHandlerData = {
    body: MonthlyBudget;
    path: {
        /**
         * The year which to update the budget of
         */
        year: string;
        /**
         * The month's budget to update. The first letter of the month's name is expected to the captalized. ie `January`
         */
        month: Month;
    };
    query?: never;
    url: '/budget/{year}/{month}';
};

export type UpdateBudgetHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to update the month's budget
     */
    500: string;
};

export type UpdateBudgetHandlerError = UpdateBudgetHandlerErrors[keyof UpdateBudgetHandlerErrors];

export type UpdateBudgetHandlerResponses = {
    /**
     * Successfully updated the month's budget
     */
    200: unknown;
};

export type ExportCsvHandlerData = {
    body?: never;
    path: {
        /**
         * The year the spending item is in
         */
        year: string;
        /**
         * The month the spending item is in
         */
        month: Month;
    };
    query?: never;
    url: '/export/{year}/{month}/csv';
};

export type ExportCsvHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get update spending item
     */
    500: string;
};

export type ExportCsvHandlerError = ExportCsvHandlerErrors[keyof ExportCsvHandlerErrors];

export type ExportCsvHandlerResponses = {
    /**
     * Spending items in CSV format
     */
    200: string;
};

export type ExportCsvHandlerResponse = ExportCsvHandlerResponses[keyof ExportCsvHandlerResponses];

export type GraphqlHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphqlHandlerResponses = {
    /**
     * GraphQL response
     */
    200: unknown;
};

export type BasicAuthHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/basic';
};

export type BasicAuthHandlerErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
};

export type BasicAuthHandlerError = BasicAuthHandlerErrors[keyof BasicAuthHandlerErrors];

export type BasicAuthHandlerResponses = {
    /**
     * Login successful. Returns a JWT token
     */
    200: string;
};

export type BasicAuthHandlerResponse = BasicAuthHandlerResponses[keyof BasicAuthHandlerResponses];

export type BasicAuthHandlerV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/basic/v2';
};

export type BasicAuthHandlerV2Errors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
};

export type BasicAuthHandlerV2Error = BasicAuthHandlerV2Errors[keyof BasicAuthHandlerV2Errors];

export type BasicAuthHandlerV2Responses = {
    /**
     * Login successful. Returns a JWT token
     */
    200: string;
};

export type BasicAuthHandlerV2Response = BasicAuthHandlerV2Responses[keyof BasicAuthHandlerV2Responses];

export type SaveNotificationSubscriptionHandlerData = {
    /**
     * The notfication subscription generated by the browser
     */
    body: NotificationSubscription;
    path?: never;
    query?: never;
    url: '/notification/save-subscription';
};

export type SaveNotificationSubscriptionHandlerResponses = {
    /**
     * Notification sent successfully
     */
    200: unknown;
};

export type SendNotificationHandlerData = {
    body: NotificationSendBody;
    path?: never;
    query?: never;
    url: '/notification/send';
};

export type SendNotificationHandlerResponses = {
    /**
     * Notification sent successfully
     */
    200: unknown;
};

export type GetSpendingItemData = {
    body?: never;
    path: {
        /**
         * The year the spending item is in
         */
        year: string;
        /**
         * The month the spending item is in
         */
        month: Month;
        /**
         * The ID of the spending item
         */
        id: string;
    };
    query?: never;
    url: '/spending-item/{year}/{month}/{id}';
};

export type GetSpendingItemErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get the requested spending item
     */
    500: string;
};

export type GetSpendingItemError = GetSpendingItemErrors[keyof GetSpendingItemErrors];

export type GetSpendingItemResponses = {
    /**
     * The request spending item
     */
    200: MonthlyBudget;
};

export type GetSpendingItemResponse = GetSpendingItemResponses[keyof GetSpendingItemResponses];

export type UpdateSpendingItemData = {
    body: MonthlyBudget;
    path: {
        /**
         * The year the spending item is in
         */
        year: string;
        /**
         * The month the spending item is in
         */
        month: Month;
        /**
         * The ID of the spending item to update
         */
        id: string;
    };
    query?: never;
    url: '/spending-item/{year}/{month}/{id}';
};

export type UpdateSpendingItemErrors = {
    /**
     * Authenication token expired. Please reauthenicate
     */
    401: string;
    /**
     * Authenication failed
     */
    403: string;
    /**
     * Failed to get update spending item
     */
    500: string;
};

export type UpdateSpendingItemError = UpdateSpendingItemErrors[keyof UpdateSpendingItemErrors];

export type UpdateSpendingItemResponses = {
    /**
     * The request spending item was Successfully updated
     */
    200: unknown;
};
