/*
 * Firefly III API v6.4.14
 *
 * This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small> 
 *
 * The version of the OpenAPI document: v6.4.14
 * Contact: james@firefly-iii.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurrenceUpdate {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Not to be confused with the description of the actual transaction(s) being created.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// First time the recurring transaction will fire.
    #[serde(rename = "first_date", skip_serializing_if = "Option::is_none")]
    pub first_date: Option<String>,
    /// Date until when the recurring transaction can fire. After that date, it's basically inactive. Use either this field or repetitions.
    #[serde(rename = "repeat_until", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub repeat_until: Option<Option<String>>,
    /// Max number of created transactions. Use either this field or repeat_until.
    #[serde(rename = "nr_of_repetitions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nr_of_repetitions: Option<Option<i32>>,
    /// Whether or not to fire the rules after the creation of a transaction.
    #[serde(rename = "apply_rules", skip_serializing_if = "Option::is_none")]
    pub apply_rules: Option<bool>,
    /// If the recurrence is even active.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "repetitions", skip_serializing_if = "Option::is_none")]
    pub repetitions: Option<Vec<models::RecurrenceRepetitionUpdate>>,
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<models::RecurrenceTransactionUpdate>>,
}

impl RecurrenceUpdate {
    pub fn new() -> RecurrenceUpdate {
        RecurrenceUpdate {
            title: None,
            description: None,
            first_date: None,
            repeat_until: None,
            nr_of_repetitions: None,
            apply_rules: None,
            active: None,
            notes: None,
            repetitions: None,
            transactions: None,
        }
    }
}

