[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/shawnyu5/common-axum?rev=v1.4.0"]
git = "https://github.com/shawnyu5/common-axum"
rev = "v1.4.0"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
