mutation saveSubscription($subscription: SubscriptionInput!) {
  saveSubscription(subscription: $subscription) {
    username
    notificationSubscription {
      endpoint
      expirationTime
      keys {
        p256Dh
        auth
      }
    }
  }
}

mutation UpdateMonthlyBudgetConfig($inputs: UpdateBudgetConfigInput!) {
  updateBudgetConfig(inputs: $inputs) {
    ... on BudgetConfig {
      __typename
      totalAllocation
      shawnPercentageAllocation
      shawnContributionAmount
      maggiePercentageAllocation
      maggieContributionAmount
    }
    ... on GraphQLErrorObject {
      __typename
      code
      message
    }
  }
}

mutation AddSpendingItemByMonth($inputs: AddSpendingItemByMonthInput!) {
  addSpendingItemByMonth(inputs: $inputs) {
    ... on MonthlyBudget {
      month
      totalSpending
      overBudgetAmount
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
      spending {
        id
        description
        amount
        date
        notes
      }
    }
    ... on GraphQLErrorObject {
      code
      message
    }
  }
}

mutation DeleteSpendingItemByID($inputs: DeleteSpendingItemByIdInput!) {
  deleteSpendingItemById(inputs: $inputs) {
    ... on MonthlyBudget {
      month
      totalSpending
      overBudgetAmount
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
      spending {
        id
        description
        amount
        date
        notes
      }
    }
    ... on GraphQLErrorObject {
      code
      message
    }
  }
}

mutation UpdateSpendingItemByID($inputs: UpdateSpendingItemByIdInput!) {
  updateSpendingItemById(inputs: $inputs) {
    ... on MonthlyBudget {
      month
      totalSpending
      overBudgetAmount
      carriedOverFrom
      budget {
        totalAllocation
        maggiePercentageAllocation
        maggieContributionAmount
        shawnPercentageAllocation
        shawnContributionAmount
      }
      spending {
        id
        description
        amount
        date
        notes
      }
    }
    ... on GraphQLErrorObject {
      code
      message
    }
  }
}
