/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["app_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the JWT token in the header. */
        get: operations["validate_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the budget information for a specific month */
        get: operations["get_month_budget_handler"];
        put?: never;
        /** Update the budget for a specific month in a specific year. This route will also ensure the `totalSpending`, and `overBudgetAmount` is up to date */
        post: operations["update_budget_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login/basic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["basic_auth_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending-item/{year}/{month}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for a spending item by time and ID */
        get: operations["get_spending_item"];
        put?: never;
        /** Update a single spending item by ID in a specific year and month. As well as updating the `totalSpending` */
        post: operations["update_spending_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Budget: {
            /** Format: int64 */
            maggie_percentage_allocation: number;
            /** Format: int64 */
            shawn_percentage_allocation: number;
            /**
             * Format: int64
             * @description Total allocated budget
             */
            total: number;
        };
        HomeResponse: {
            version: string;
        };
        /** @enum {string} */
        Month: "January" | "February" | "March" | "April" | "May" | "June" | "July" | "August" | "September" | "October" | "November" | "December";
        /** @description Budget details for single month */
        MonthlyBudget: {
            /** @description Budget details */
            budget: components["schemas"]["Budget"];
            carriedOverFrom?: null | components["schemas"]["Month"];
            /** @description The month */
            month: components["schemas"]["Month"];
            /**
             * Format: int64
             * @description Amount over budget for the month. 0 means not over budget.
             */
            overBudgetAmount: number;
            /** @description List of spent items */
            spending: components["schemas"]["SpendingItem"][];
            /**
             * Format: int64
             * @description Total spending for the month
             */
            totalSpending: number;
        };
        /** @description A single transaction */
        SpendingItem: {
            /**
             * Format: int64
             * @description The dollar amount
             */
            amount: number;
            /** @description The date */
            date: string;
            /** @description Description of the purchase */
            description: string;
            /** @description A unique identifier */
            id: string;
            /** @description Additional notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version of the server */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
            /** @description Failed to get the vesion of the server */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    validate_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request spending item was Successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Failed to get update spending item */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_month_budget_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The year which to get the budget of */
                year: string;
                /** @description The month's budget to get. The first letter of the month's name is expected to the captalized. ie `January` */
                month: components["schemas"]["Month"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested month's budget. If the request month does not have any budget records, this route will iterate back till either no more months to check, a budget is encountered. The returned budget will have no spending, all the fields are correct, and matches the request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyBudget"];
                };
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description All months, the requested month and before does not contain any monthly budget */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Failed to get the requested month's budget */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    update_budget_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The year which to get the budget of */
                year: string;
                /** @description The month's budget to get. The first letter of the month's name is expected to the captalized. ie `January` */
                month: components["schemas"]["Month"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyBudget"];
            };
        };
        responses: {
            /** @description Successfully updated the month's budget */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyBudget"];
                };
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Failed to update the month's budget */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    basic_auth_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login successful. Returns a JWT token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_spending_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The year the spending item is in */
                year: string;
                /** @description The month the spending item is in */
                month: components["schemas"]["Month"];
                /** @description The ID of the spending item */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request spending item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyBudget"];
                };
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Failed to get the requested spending item */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    update_spending_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The year the spending item is in */
                year: string;
                /** @description The month the spending item is in */
                month: components["schemas"]["Month"];
                /** @description The ID of the spending item to update */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyBudget"];
            };
        };
        responses: {
            /** @description The request spending item was Successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenication token expired. Please reauthenicate */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Authenication failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Failed to get update spending item */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
