name: Semantic release and publish image
on:
  push:
    branches:
      - "master"
      # - "develop"

permissions:
  contents: read
  packages: write

jobs:
  release_deploy:
    name: Semantic release and deploy backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic release dry run
        id: dry_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: codfish/semantic-release-action@v4.0.1
        with:
          dry-run: true

      - name: Next release version
        run: |
          echo ${{ steps.dry_run.outputs.release-version }}

      - name: Update version in Cargo.toml
        if: steps.dry_run.outputs.new-release-published == 'true'
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "backend/Cargo.toml"
          key: "package.version"
          value: "${{ steps.dry_run.outputs.release-version }}"

      # - name: Setup rust toolling
      #   if: steps.dry_run.outputs.new-release-published == 'true'
      #   uses: moonrepo/setup-rust@v1

      - name: Semantic release
        id: semantic_release
        if: steps.dry_run.outputs.new-release-published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: codfish/semantic-release-action@v4.0.1

      # - name: Update values.yaml
      #   if: steps.dry_run.outputs.new-release-published == 'true'
      #   uses: fjogeleit/yaml-update-action@v0.16.1
      #   with:
      #     valueFile: "docker-compose.yml"
      #     propertyPath: "services.budget_tool.image"
      #     value: ghcr.io/shawnyu5/budget_tool:${{ steps.semantic_release.outputs.release-version }}
      #     commitChange: false
      #
      - name: Set up Docker
        if: steps.dry_run.outputs.new-release-published == 'true'
        uses: docker/setup-buildx-action@v3.12.0

      - name: Log in to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup flyctl
        if: steps.dry_run.outputs.new-release-published == 'true'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Push new image to ghcr
        if: steps.dry_run.outputs.new-release-published == 'true'
        uses: docker/build-push-action@v6.18.0
        with:
          context: backend
          push: true
          tags: ghcr.io/shawnyu5/budget_tool_backend:${{ steps.semantic_release.outputs.release-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy backend
        if: steps.dry_run.outputs.new-release-published == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd backend
          flyctl deploy --local-only --config fly.prod.toml
